Repository briehq/brie-extension, pull requests merged in 2025-05, with the labels that each got.

#133 #125: Move Sensitive Info Redaction into addOrMergeRecords Method
  chrome-extension/package.json
  chrome-extension/src/background/index.ts
  chrome-extension/src/utils/manage-records.util.ts
  package.json
  packages/dev-utils/package.json
  packages/env/lib/index.ts
  packages/env/package.json
  packages/hmr/package.json
  packages/i18n/package.json
  packages/shared/lib/constants/index.ts
  packages/shared/lib/constants/sensitive-keywords.constants.ts
  packages/shared/lib/constants/sensitive-patterns.constants.ts
  packages/shared/lib/utils/index.ts
  packages/shared/lib/utils/redact-sensitive-info.util.ts
  packages/shared/lib/utils/traverse-information.util.ts
  packages/shared/package.json
  packages/storage/package.json
  packages/store/package.json
  packages/tailwindcss-config/package.json
  packages/tsconfig/package.json
  packages/ui/package.json
  packages/vite-config/package.json
  packages/zipper/package.json
  pages/content-runtime/package.json
  pages/content-ui/package.json
  pages/content-ui/src/content.tsx
  pages/content/package.json
  pages/content/src/interceptors/application/cookies.interceptor.ts
  pages/content/src/interceptors/application/local-storage.interceptor.ts
  pages/content/src/interceptors/application/session-storage.interceptor.ts
  pages/content/src/interceptors/network/fetch.interceptor.ts
  pages/content/src/interceptors/network/xhr.interceptor.ts
  pages/content/src/sampleFunction.ts
  pages/devtools-panel/package.json
  pages/devtools/package.json
  pages/new-tab/package.json
  pages/options/package.json
  pages/popup/package.json
  pages/side-panel/package.json
  pnpm-lock.yaml
  tests/e2e/package.json
  vite-env.d.ts
Labels: enhancement, improvements, refactor

#136 refactor(#108): remove options module
  chrome-extension/manifest.ts
  pages/side-panel/index.html
  pages/side-panel/package.json
  pages/side-panel/public/logo_vertical.svg
  pages/side-panel/public/logo_vertical_dark.svg
  pages/side-panel/src/SidePanel.css
  pages/side-panel/src/SidePanel.tsx
  pages/side-panel/src/index.css
  pages/side-panel/src/index.tsx
  pages/side-panel/tailwind.config.ts
  pages/side-panel/tsconfig.json
  pages/side-panel/vite.config.mts
  tests/e2e/specs/page-options.test.ts
  tests/e2e/specs/page-side-panel.test.ts
Labels: enhancement, good first issue, refactor

#144 refactor(#107): remove devtools panel module
  pages/devtools-panel/index.html
  pages/devtools-panel/package.json
  pages/devtools-panel/public/logo_horizontal.svg
  pages/devtools-panel/public/logo_horizontal_dark.svg
  pages/devtools-panel/src/Panel.css
  pages/devtools-panel/src/Panel.tsx
  pages/devtools-panel/src/index.css
  pages/devtools-panel/src/index.tsx
  pages/devtools-panel/tailwind.config.ts
  pages/devtools-panel/tsconfig.json
  pages/devtools-panel/vite.config.mts
  tests/e2e/specs/page-dev-tools.test.ts
Labels: enhancement, good first issue, refactor

#146 refactor(#105): remove new tab module
  chrome-extension/manifest.ts
  package.json
  packages/ui/package.json
  pages/new-tab/index.html
  pages/new-tab/package.json
  pages/new-tab/public/logo_horizontal.svg
  pages/new-tab/public/logo_horizontal_dark.svg
  pages/new-tab/src/NewTab.css
  pages/new-tab/src/NewTab.scss
  pages/new-tab/src/NewTab.tsx
  pages/new-tab/src/index.css
  pages/new-tab/src/index.tsx
  pages/new-tab/tailwind.config.ts
  pages/new-tab/tsconfig.json
  pages/new-tab/vite.config.mts
  tests/e2e/package.json
  tests/e2e/specs/page-new-tab.test.ts
Labels: enhancement, good first issue, refactor

#147 feature(#97): add codeql
  .github/workflows/codeql.yml
Labels: enhancement

#148 feat(#67): add russian language support
  docs/readme/ru.md
  packages/i18n/locales/ru/messages.json
Labels: enhancement, improvements, feature

#149 feat(#45): add support for italian language
  docs/readme/it.md
  packages/i18n/locales/it/messages.json
Labels: enhancement, feature

#150 feat(#44): add support for ukrainian ua language
  docs/readme/uk.md
  packages/i18n/locales/uk/messages.json
Labels: enhancement, good first issue, feature

#153 refactor(#152): improved the way events are captured
  README.md
  chrome-extension/src/background/index.ts
  chrome-extension/src/utils/manage-records.util.ts
  chrome-extension/src/utils/plugins/make-manifest-plugin.ts
  chrome-extension/tsconfig.json
  chrome-extension/vite.config.mts
  packages/i18n/locales/en/messages.json
  packages/i18n/locales/es/messages.json
  packages/i18n/locales/hi/messages.json
  packages/i18n/locales/it/messages.json
  packages/i18n/locales/ro/messages.json
  packages/i18n/locales/ru/messages.json
  packages/i18n/locales/uk/messages.json
  packages/shared/lib/constants/non-production-keywords.constants.ts
  packages/shared/lib/constants/sensitive-keywords.constants.ts
  pages/content-ui/src/content.tsx
  pages/content/src/constants/clickable-tags.constants.ts
  pages/content/src/interceptors/events/events.interceptor.ts
  pages/content/src/utils/events/element-clickable.util.ts
  pages/content/src/utils/events/find-clickable-element.util.ts
  pages/content/src/utils/events/index.ts
  pages/content/src/utils/events/should-skip-click.util.ts
  pages/content/src/utils/events/should-skip-input-tracking.util.ts
  pages/popup/src/components/ui/skeleton.ui.tsx
  pages/popup/src/popup-content.tsx
  pnpm-lock.yaml
Labels: improvements, refactor

#157 feature(#36): add emulation, network, locale, memory and context info to metadata
  pages/content/src/interceptors/events/events.interceptor.ts
  pages/content/src/interfaces/events/battery-info.interface.ts
  pages/content/src/interfaces/events/browser-info.interface.ts
  pages/content/src/interfaces/events/extension-context.interface.ts
  pages/content/src/interfaces/events/index.ts
  pages/content/src/interfaces/events/language-info.interface.ts
  pages/content/src/interfaces/events/memory-info.interface.ts
  pages/content/src/interfaces/events/network-info.interface.ts
  pages/content/src/interfaces/events/os-info.interface.ts
  pages/content/src/interfaces/events/system-info.interface.ts
  pages/content/src/utils/events/index.ts
  pages/content/src/utils/events/system-info.util.ts
  pages/content/src/utils/events/system-info/battery-info.util.ts
  pages/content/src/utils/events/system-info/detect-emulation.util.ts
  pages/content/src/utils/events/system-info/extension-context.util.ts
  pages/content/src/utils/events/system-info/incognito-status.util.ts
  pages/content/src/utils/events/system-info/index.ts
  pages/content/src/utils/events/system-info/language-info.util.ts
  pages/content/src/utils/events/system-info/memory-info.util.ts
  pages/content/src/utils/events/system-info/network-info.util.ts
  pages/content/src/utils/events/system-info/system-info.util.ts
  pages/content/src/utils/events/system-info/user-agent.util.ts
  pages/content/src/utils/events/system-info/zoom-level.util.ts
Labels: improvements, refactor, feature, requires fe changes

#160 refactor(#34): improve redact sensitive keywords and values
  packages/shared/lib/constants/non-production-keywords.constants.ts
  packages/shared/lib/constants/sensitive-keywords.constants.ts
  packages/shared/lib/utils/redact-sensitive-info.util.ts
Labels: bug, improvements, refactor
