Repository briehq/brie-extension, pull requests merged in 2025-06, with the labels that each got.

#163 bug(#24): prompt user to refresh tab after extension install or update
  chrome-extension/src/background/index.ts
  packages/i18n/locales/en/messages.json
  packages/i18n/locales/es/messages.json
  packages/i18n/locales/hi/messages.json
  packages/i18n/locales/it/messages.json
  packages/i18n/locales/ro/messages.json
  packages/i18n/locales/ru/messages.json
  packages/i18n/locales/uk/messages.json
  packages/shared/lib/utils/safe-post-message.util.ts
  packages/storage/lib/impl/index.ts
  packages/storage/lib/impl/pending-reload-tabs.storage.ts
  pages/content-ui/src/components/annotation/annotation-container.tsx
  pages/popup/src/components/capture/screenshot-button.capture.tsx
Labels: bug, improvements, refactor

#166 bug: redact sensitive info for every domain outside of localhost
  .example.env
  chrome-extension/src/background/index.ts
  package.json
  packages/shared/lib/constants/non-production-keywords.constants.ts
Labels: bug, improvements, refactor

#175 Fix: Text Not Visible on Description Input in Annotation View
  packages/ui/lib/components/ui/textarea.tsx
Labels: bug, improvements

#176 refactor(readme): update the run extension section
  docs/CONTRIBUTING.md
  pages/content-ui/public/brie-icon-64x64.png
  pages/content/public/brie-icon-64x64.png
Labels: documentation, improvements, refactor

#186 bug(#77): improved github greetings message
  .github/auto_assign.yml
  .github/workflows/greetings.yml
Labels: improvements, refactor

#190 bug(#178): no sandbox api for contributors to test extension
  .example.env
  .github/workflows/greetings.yml
  bash-scripts/set_global_env.sh
  docs/CONTRIBUTING.md
  packages/env/README.md
  pages/popup/src/components/ui/header.ui.tsx
Labels: improvements, feature

#196 bug(#184): duplicate eslint configs causing conflicts
  .eslintignore
  .eslintrc
  .github/workflows/lint.yml
  .prettierrc
  eslint.config.js
  package.json
  pnpm-lock.yaml
Labels: bug, improvements, refactor

#232 refactor(#223): improved the dark theme styles
  chrome-extension/src/background/index.ts
  packages/storage/lib/impl/pending-reload-tabs.storage.ts
  packages/tailwindcss-config/tailwind.config.ts
  packages/ui/global.css
  packages/ui/lib/components/ui/dialog-legacy.tsx
  pages/content-ui/src/components/annotation/annotation-sidebar.feature.tsx
  pages/content-ui/src/content.tsx
  pages/popup/src/components/capture/screenshot-button.capture.tsx
  pages/popup/src/components/slices-history/button.slices-history.tsx
  pages/popup/src/components/ui/beta-notifier.ui.tsx
Labels: high priority

#233 bug(#33 & #230): inject globally radix and sonner styles
  packages/ui/global.css
  packages/ui/lib/components/ui/checkbox.tsx
  packages/ui/lib/components/ui/command.tsx
  packages/ui/lib/components/ui/context-menu.tsx
  packages/ui/lib/components/ui/dialog.tsx
  packages/ui/lib/components/ui/form.tsx
  packages/ui/lib/components/ui/index.ts
  packages/ui/lib/components/ui/label.tsx
  packages/ui/lib/components/ui/popover.tsx
  packages/ui/lib/components/ui/radio-group.tsx
  packages/ui/lib/components/ui/scroll-area.tsx
  packages/ui/lib/components/ui/separator.tsx
  packages/ui/lib/components/ui/sonner.tsx
  packages/ui/lib/components/ui/tooltip.tsx
  packages/ui/lib/utils.ts
  packages/ui/package.json
  pages/content-ui/src/App.tsx
  pages/content-ui/src/components/annotation/annotation-sidebar.feature.tsx
  pnpm-lock.yaml
Labels: improvements, refactor, high priority
